# Inspired by https://github.com/succinctlabs/plonky2-ecdsa/blob/main/.github/workflows/continuous-integration.yml

name: Rust CI

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "**"

jobs:  
  test:
    name: Test Examples
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        id: rustc-toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: rust-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: rustc-test-${{ steps.rustc-toolchain.outputs.rustc_hash }}-cargo-${{ hashFiles('**/Cargo.toml') }}

      - name: Run all examples
        shell: bash
        env:
          RUSTFLAGS: -Ctarget-cpu=native
        run: |
          # Find all Rust files in examples and its subdirectories, excluding utils
          for file in $(find examples -name "*.rs" -not -path "*/utils/*"); do
            # Extract example name without path and extension
            example=$(basename "$file" .rs)
            echo "Running example: $example"
            if [ "$example" = "merkle_tree" ] || [ "$example" = "merkle_tree_average" ] || [ "$example" = "merkle_tree_batch" ] || [ "$example" = "merkle_tree_recursive_verify" ] || [ "$example" = "merkle_tree_recursive_batch" ] || [ "$example" = "merkle_tree_recursive_pairwise" ]; then
              cargo run --release --example "$example" -- 2
            else
              cargo run --release --example "$example" -- -vv
            fi
          done

  lints:
    name: Formatting and Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        id: rustc-toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: rust-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: rustc-lints-${{ steps.rustc-toolchain.outputs.rustc_hash }}-cargo-${{ hashFiles('**/Cargo.toml') }}

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
        env:
          CARGO_INCREMENTAL: 1

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features --all-targets -- -D warnings -A incomplete-features
        env:
          # Seems necessary until https://github.com/rust-lang/rust/pull/115819 is merged.
          CARGO_INCREMENTAL: 0